{
    "ProblemRandmonizationParameters" : {
        "MIN_NUM_SHIFTS_PER_WEEK" : 6,
        "MAX_NUM_SHIFTS_PER_WEEK" : 12,

        "MIN_NUM_OF_TAS_REQUIRED_PER_SHIFT" : 2,
        "MAX_NUM_OF_TAS_REQUIRED_PER_SHIFT" : 3,

        # Constants for random TA generation
        "MIN_NUM_OF_SHIFT_PER_TA_PER_WEEK" : 0,
        # MAX_NUM_OF_SHIFT_PER_TA_PER_WEEK : ... # This value will be set dynamically based on the total TA demand and number of TAs (as to not over-constrain the problem)

        "MIN_TA_SKILL_LEVEL" : 1,
        "MAX_TA_SKILL_LEVEL" : 3,

        "MIN_NUM_OF_UNAVAILABLE_SHIFTS_DIV"   : 0,
        "MAX_NUM_OF_UNAVAILABLE_SHIFTS_DIV"   : 20,    # in pecentage of the total weekly shifts

        "MIN_NUM_OF_DESIRED_SHIFTS_DIV"       : 0,     # in pecentage of the total weekly shifts
        "MAX_NUM_OF_DESIRED_SHIFTS_DIV"       : 40,    # in pecentage of the total weekly shifts

        "MIN_NUM_OF_UNDESIRED_SHIFTS_DIV"     : 0,     # in pecentage of the total weekly shifts
        "MAX_NUM_OF_UNDESIRED_SHIFTS_DIV"     : 30,    # in pecentage of the total weekly shifts
    },

    "TimetableSolver" : {
        "constraint_version"    : "default",
        "logger"                : logging.Logger, 
        "random_seed"           : null,
        "path_to_config_xml"    : "",
        "use_config_xml"        : false
                    },


    

    

}